version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    container_name: postgres_chat
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - fullstack
    volumes:
      - data:/var/lib/postgresql/data

  parler-backend:
    container_name: go-server
    build:
      context: .
      dockerfile: server.Dockerfile
    env_file: 
      - .env
    depends_on:
      - db
    networks:
      - fullstack
    ports:
      - "8080:8080"
volumes:
  data:
    driver: local
networks:
  fullstack:
    driver: bridge
